Repository maplelabs/opensearch-scaling-manager, pull requests merged in 2023-02, with the labels that each got.

#305 Close Response Body & Read purge time
  cluster/cluster_level_parameters.go
  config.yaml
  config/config.go
Labels: Recommendation

#306 Close response Body & read purge time from user
  fetchmetrics/fetchClusterMetrics.go
  fetchmetrics/fetchMetrics.go
  fetchmetrics/fetchNodeMetrics.go
  fetchmetrics/purgeOldDocs.go
Labels: FetchMetrics

#304 Opensearch utility close resp body
  utilities/utilities.go
Labels: enhancement

#303 Close response Body & move ansible_scripts dir
  ansible_scripts/ansible.cfg
  ansible_scripts/docs.py
  ansible_scripts/group_vars/all/all.yml
  ansible_scripts/roles/scale_down/defaults/main.yml
  ansible_scripts/roles/scale_down/handlers/main.yml
  ansible_scripts/roles/scale_down/tasks/main.yml
  ansible_scripts/roles/scale_down/vars/main.yml
  ansible_scripts/roles/scale_up/defaults/main.yml
  ansible_scripts/roles/scale_up/handlers/main.yml
  ansible_scripts/roles/scale_up/tasks/ansible.cfg
  ansible_scripts/roles/scale_up/tasks/install_ansible.yml
  ansible_scripts/roles/scale_up/tasks/main.yml
  ansible_scripts/roles/scale_up/tasks/opensearch.yml
  ansible_scripts/roles/scale_up/tasks/security.yml
  ansible_scripts/roles/scale_up/tasks/tune.yml
  ansible_scripts/roles/scale_up/templates/internal_users.yml
  ansible_scripts/roles/scale_up/templates/jvm.options
  ansible_scripts/roles/scale_up/templates/opensearch-multi-node.yml
  ansible_scripts/roles/scale_up/templates/opensearch.service
  ansible_scripts/roles/scale_up/templates/security_conf.yml
  ansible_scripts/roles/scale_up/templates/tlsconfig.yml
  ansible_scripts/scaleDownPlaybook.yml
  ansible_scripts/scaleUpPlaybook.yml
  main.go
  provision/callAnsible.go
  provision/provision.go
  provision/state_functions.go
Labels: Provision

#301 RecommendationEngine test case
  recommendation/recommendation_test.go
Labels: Recommendation

#307 Accelerated time for shard rebalancing
  simulator/src/app.py
  simulator/src/cluster.py
Labels: Simulator

#308 Removed debug code
  main.go
Labels: enhancement

#328 Ansible config updates
  ansible_scripts/group_vars/all/all.yml
  ansible_scripts/roles/scale_down/tasks/main.yml
  ansible_scripts/roles/scale_up/tasks/security.yml
  ansible_scripts/roles/scale_up/templates/internal_users.yml
  ansible_scripts/roles/scale_up/templates/opensearch-multi-node.yml
  provision/callAnsible.go
  provision/provision.go
Labels: Provision

#327 read ansible config
  config.yaml
  config/config.go
Labels: Recommendation

#334 Check cluster health for scale down
  provision/trigger.go
Labels: Provision

#331 Changed warning to debug stmt
  recommendation/recommendationEngine.go
Labels: Recommendation

#337 Index Addition and Roll over due to age
  simulator/src/app.py
  simulator/src/cluster.py
  simulator/src/config.yaml
  simulator/src/config_parser.py
  simulator/src/index.py
  simulator/src/index_addittion.py
  simulator/src/open_search_simulator.py
  simulator/src/plotter.py
  simulator/src/schema.py
Labels: Simulator

#329 - Added test case for config.go after code restructure
  config/config.go
  config/config_test.go
Labels: Recommendation

#344 Add decision period to the ruleResponsible string
  config.yaml
  recommendation/recommendationEngine.go
Labels: Recommendation

#343 Wait for next provision & time update
  provision/provision.go
  provision/state_functions.go
  provision/trigger.go
Labels: Provision

#341 Index name Update & mappings file update
  opensearchUtils/mappings.json
  opensearchUtils/osConnection.go
Labels: enhancement

#340 Added field to support SF UI
  fetchmetrics/fetchClusterMetrics.go
  fetchmetrics/fetchNodeMetrics.go
Labels: FetchMetrics

#347 wait_for refresh of index and fix nil map issue
  opensearchUtils/apiCalls.go
  utilities/utilities.go
Labels: enhancement

#346 Max|Min Nodes check for provisioning
  cluster/cluster_level_parameters.go
  config.yaml
Labels: Recommendation

#345 Max|Min Nodes Check & move logic to function
  provision/trigger.go
Labels: Provision

#348 Check for reloacting shards
  provision/provision.go
  provision/trigger.go
Labels: Provision

#349 Changes to call simulator methods
  main.go
  provision/trigger.go
Labels: Provision

#352 Bug fix
  provision/trigger.go
Labels: Provision

#354 Code optimozation & Pass map instead of variables file to ansible script
  ansible_scripts/ansible.cfg
  provision/callAnsible.go
  provision/provision.go
Labels: Provision

#355 Ansible extra vars as map[string]interface{}
  cluster/cluster_level_parameters.go
  config/config.go
Labels: Recommendation

#356 Add launchTemplate details
  config.yaml
  config/config.go
Labels: Recommendation

#357 Terminate the instance
  ansible_scripts/roles/scale_down/tasks/main.yml
  provision/awsScale.go
  provision/provision.go
Labels: Provision

#353 CLI commands to start/stop Scaling Manager
  cluster/cluster_level_parameters.go
  cluster_sim/cluster_level_parameters.go
  cmd/maincmd.go
  cmd/start.go
  cmd/stop.go
  config/config.go
  fetchmetrics/fetchClusterMetrics.go
  fetchmetrics/fetchMetrics.go
  fetchmetrics/fetchNodeMetrics.go
  fetchmetrics/purgeOldDocs.go
  go.mod
  opensearchUtils/osConnection.go
  provision/callAnsible.go
  provision/provision.go
  provision/state_functions.go
  provision/trigger.go
  recommendation/recommendationEngine.go
  scaleManager/main.go
  scale_manager.go
  utilities/utilities.go
Labels: enhancement

#363 Move callAnsible into ansible package
  ansible_scripts/callAnsible.go
  ansible_scripts/install_scaling_manager.yaml
  provision/provision.go
Labels: Provision

#365 Read pemfile path from config
  provision/provision.go
Labels: Provision

#366 Added pem file path in config file
  config.yaml
  config/config.go
Labels: Recommendation

#373 Ansible and pem file copy
  GNUmakefile
  install_scaling_manager.yaml
Labels: devops

#372 Read AWS region
  config.yaml
  config/config.go
Labels: Recommendation

#371 Fixed nodeMap Interface issue
  utilities/utilities.go
Labels: enhancement

#370 Fix integration issues
  ansible.cfg
  ansible_scripts/ansible.cfg
  ansible_scripts/callAnsible.go
  ansible_scripts/group_vars/all/all.yml
  ansible_scripts/roles/scale_up/tasks/main.yml
  ansible_scripts/roles/scale_up/tasks/security.yml
  ansible_scripts/scaleUpPlaybook.yml
  provision/awsScale.go
  provision/provision.go
  provision/state_functions.go
Labels: Provision

#376 Remove validation for MonitorWithLogs
  config/config.go
Labels: Recommendation

#375 Fix issues:
  ansible_scripts/roles/scale_down/tasks/main.yml
  ansible_scripts/roles/scale_up/tasks/opensearch.yml
  ansible_scripts/roles/scale_up/tasks/security.yml
  ansible_scripts/scaleDownPlaybook.yml
  ansible_scripts/scaleUpPlaybook.yml
  provision/provision.go
Labels: Provision

#378 Updated Stop logic
  cmd/stop.go
Labels: enhancement

#379 Change ownership of copied file
  ansible_scripts/roles/scale_up/tasks/security.yml
Labels: Provision

#380 Check new node addition
  ansible_scripts/roles/scale_up/tasks/security.yml
  provision/provision.go
  provision/trigger.go
Labels: Provision

#383 Remove host after scaledown
  ansible_scripts/scaleDownPlaybook.yml
Labels: Provision

#385 Fixed duplicate host entry
  ansible_scripts/roles/scale_up/tasks/main.yml
  ansible_scripts/scaleUpPlaybook.yml
Labels: Provision

#386 New node name change
  provision/provision.go
  provision/trigger.go
Labels: Provision

#388 Install Scaling Manager on new node
  ansible_scripts/callAnsible.go
  provision/provision.go
Labels: Provision

#390 Added error log
  provision/provision.go
Labels: Provision

#394 Read group from user config
  config.yaml
  config/config.go
Labels: Recommendation

#393 Fix issues
  ansible_scripts/group_vars/all/all.yml
  ansible_scripts/roles/scale_down/tasks/main.yml
  ansible_scripts/roles/scale_up/tasks/opensearch.yml
  ansible_scripts/roles/scale_up/tasks/security.yml
  ansible_scripts/roles/scale_up/templates/opensearch.service
  ansible_scripts/scaleDownPlaybook.yml
  ansible_scripts/scaleUpPlaybook.yml
  provision/provision.go
  provision/trigger.go
Labels: Provision

#395 Check node join before scaleup is marked complete
  provision/provision.go
Labels: Provision

#398 Update fileWatch() & update secret first
  crypto/crypto_controller.go
  scaleManager/main.go
Labels: crypto

#404 Cleanup and format config.yaml
  config.yaml
Labels: Recommendation

#403 Add new empty custom role
  ansible_scripts/roles/custom_role/README.md
  ansible_scripts/roles/custom_role/defaults/main.yml
  ansible_scripts/roles/custom_role/handlers/main.yml
  ansible_scripts/roles/custom_role/meta/main.yml
  ansible_scripts/roles/custom_role/tasks/main.yml
  ansible_scripts/roles/custom_role/tests/inventory
  ansible_scripts/roles/custom_role/tests/test.yml
  ansible_scripts/roles/custom_role/vars/main.yml
  ansible_scripts/scaleUpPlaybook.yml
Labels: Provision

#407 Fix issue
  scaleManager/main.go
Labels: crypto

#409 Fix issue.
  provision/awsScale.go
Labels: crypto

#410 Decrypt once in every provision
  provision/provision.go
Labels: crypto

#408 sync with config.yaml
  cluster/cluster_level_parameters.go
Labels: Recommendation

#411 Fix bug
  crypto/crypto_controller.go
Labels: crypto

#412 Remove exists check for file
  install_scaling_manager.yaml
Labels: devops

#413 Bug fix
  scaleManager/main.go
Labels: crypto

#414 Change the encode and decode logic to base32 from base64
  crypto/crypto_controller.go
Labels: crypto

#415 Check for config file change if not master
  scaleManager/main.go
Labels: crypto

#416 Remove gather_facts
  ansible_scripts/scaleUpPlaybook.yml
Labels: Provision
