Repository maplelabs/opensearch-scaling-manager, pull requests merged in 2023-03, with the labels that each got.

#359 Added readme file for OpenSearch Scaling Manager
  README.md
  docs/readme_simulator.md
Labels: documentation

#419 Shard and occurrences
  cluster/cluster_level_parameters.go
  config.yaml
  fetchmetrics/fetchClusterMetrics.go
  recommendation/recommendationEngine.go
Labels: Recommendation

#420 Ticker update
  fetchmetrics/fetchMetrics.go
  provision/awsScale.go
  scaleManager/main.go
Labels: Provision

#421 -Added details on Readme
  README.md
Labels: documentation

#423 Wait for shards
  cluster/cluster_level_parameters.go
  fetchmetrics/fetchClusterMetrics.go
  opensearchUtils/apiCalls.go
  provision/provision.go
  provision/trigger.go
Labels: Provision

#424 IAM Role based session
  config.yaml
  config/config.go
  crypto/crypto_controller.go
  provision/awsScale.go
Labels: Provision

#426 Minor bug fix
  provision/awsScale.go
Labels: Provision

#428 update_secret
  provision/provision.go
Labels: Provision

#436 JVM Allocation changes
  ansible_scripts/scaleUpPlaybook.yml
  config.yaml
  config/config.go
Labels: bug, Recommendation

#437 [BUG] jvm options copy
  ansible_scripts/roles/scale_up/tasks/opensearch.yml
Labels: bug

#422 - Added images, Brief explanation of ScalingManager
  README.md
  images/Basic_flow_ScalingManager.png
  images/Detailed_flow_ScalingManager.png
  images/Scale_up-Scale_down.png
  images/ScalingManager_Architecture.png
Labels: documentation

#440 - Replaced web url of images to link from github.
  README.md
Labels: documentation

#443 Remove TotalShards recommendation
  cluster/cluster_level_parameters.go
  config.yaml
  recommendation/recommendationEngine.go
Labels: bug

#444 Fixed Panic on Application start
  cluster/cluster_level_parameters.go
  recommendation/recommendationEngine.go
Labels: bug

#446 ShardsPerGB
  cluster/cluster_level_parameters.go
  fetchmetrics/fetchNodeMetrics.go
  recommendation/recommendationEngine.go
Labels: enhancement, Recommendation

#447 Resolve cyclic imports
  cluster/cluster_level_parameters.go
  config/config.go
  fetchmetrics/fetchClusterMetrics.go
  provision/provision.go
  recommendation/recommendationEngine.go
  scaleManager/main.go
Labels: Recommendation

#448 Reroute/scaleDownLog/MaxHeap
  ansible_scripts/docs.py
  ansible_scripts/scaleUpPlaybook.yml
  opensearchUtils/apiCalls.go
  opensearchUtils/osConnection.go
  provision/provision.go
Labels: enhancement

#450 Syntax fix
  ansible_scripts/docs.py
Labels: bug

#455 Bug fix
  config.yaml
Labels: bug

#456 Add limits for polling intervals
  config/config.go
Labels: enhancement

#462 Resolving issue with copy command.
  install_scaling_manager.yaml
Labels: bug

#459 New scale down logic
  ansible_scripts/docs.py
  ansible_scripts/roles/scale_down/tasks/main.yml
Labels: Provision

#463 Move instance status check
  provision/awsScale.go
  provision/provision.go
  provision/state_functions.go
  recommendation/recommendationEngine.go
Labels: Provision

#465 Install scaling_manager before OS config
  provision/provision.go
Labels: enhancement, Provision

#13 [recommendation_file_watch]
  main.go
Labels: Recommendation

#144 Added function to fetch time corresponding to first data point generation
  simulator/src/app.py
Labels: Simulator

#151 Simulate Node removal through endpoint
  simulator/readme.md
  simulator/src/app.py
  simulator/src/cluster.py
Labels: Simulator

#185 Restructured Simulator to accommodate index, node and shard granularity
  simulator/src/app.py
  simulator/src/cluster.py
  simulator/src/config.yaml
  simulator/src/constants.py
  simulator/src/index.py
  simulator/src/node.py
  simulator/src/open_search_simulator.py
  simulator/src/schema.py
  simulator/src/shard.py
Labels: Simulator

#187 Simulator bug
  simulator/src/app.py
  simulator/src/plotter.py
Labels: Simulator

#225 Added timeit decorator to calculate the timing
  simulator/src/open_search_simulator.py
  simulator/src/plotter.py
Labels: Simulator

#302 RecommendationEngine test case
  recommendation/recommendation_test.go
Labels: Recommendation

#470 Fix install scaling manager bug
  ansible_scripts/callAnsible.go
  ansible_scripts/install_scaling_manager.yaml
  provision/provision.go
Labels: bug

#479 Moved ansible changes to root dir
  ansible_scripts/install_scaling_manager.yaml
  install_scaling_manager.yaml
Labels: Provision

#481 Bug fix
  crypto/crypto_controller.go
Labels: bug

#484 Increase wait time for node to join the cluster
  provision/provision.go
Labels: enhancement, Provision

#486 Updated the rules
  config.yaml
Labels: Recommendation

#487 Added heap util
  config.yaml
  crypto/crypto_controller.go
Labels: Recommendation

#491 Indentation bug fix
  config.yaml
Labels: bug

#492 Changed disk util rule to 75% in config.yaml
  config.yaml
Labels: enhancement

#471 Added trouble shoot guide, contributions to README.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  docs/Code of conduct.md
  docs/Contribution.md
  docs/Guidelines.md
  docs/Scaling Manager Trouble Shooting.md
  images/Basic_flow_Scaling_Manager.png
  images/Detailed_flow_Scaling_Manager.png
  images/Scale_up_Scale_down.png
  images/Scaling_Manager_Architecture.png
Labels: documentation

#485 Simulator: Improve readme
  images/Simulator.png
  simulator/readme.md
Labels: documentation, Simulator

#500 Restructure readme.md
  README.md
  docs/Code of conduct.md
  docs/Config.md
  docs/Contribution.md
  docs/Design_document.md
  docs/Guidelines.md
  docs/Run Scaling Manager.md
  docs/Scaling Manager Trouble Shooting.md
  images/Basic_flow_Scaling_Manager.png
  images/Detailed_flow_Scaling_Manager.png
  images/Scale_up_Scale_down.png
  images/Scaling_Manager_Architecture.png
Labels: documentation

#497 Query bug fix
  cluster/cluster_level_parameters.go
  recommendation/recommendationEngine.go
Labels: bug

#501 Resolve error while loading image in readme.md
  README.md
  docs/CodeOfConduct.md
  docs/Config.md
  docs/Contribution.md
  docs/DesignArchitecture.md
  docs/Guidelines.md
  docs/ReadmeSimulator.md
  docs/RunScalingManager.md
  docs/ScalingManagerTroubleShooting.md
  images/BasicFlowScalingManager.png
  images/DetailedFlowScalingManager.png
  images/ScaleUpScaleDown.png
  images/ScalingManagerArchitecture.png
Labels: documentation

#502 Changes to Design Architecture headings
  docs/DesignArchitecture.md
Labels: documentation

#503 Refactor Simulator
  simulator/readme.md
  simulator/src/app.py
  simulator/src/constants.py
Labels: Simulator

#510 Start opensearch after custom role is executed
  ansible_scripts/roles/scale_down/tasks/main.yml
  ansible_scripts/roles/scale_up/tasks/security.yml
  ansible_scripts/scaleDownPlaybook.yml
  ansible_scripts/scaleUpPlaybook.yml
Labels: enhancement, Provision
